name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  provider: ^6.0.5
  flutter_staggered_animations: ^1.0.0
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  flutter_markdown: ^0.7.6+2

  # Google AI & APIs
  google_generative_ai: ^0.4.6
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # HTTP Requests
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/keys/vertex_ai_key.json
    - assets/images/crypto.jpg
    - assets/images/global_economy.jpg
    - assets/images/stock_market.jpg
    - assets/images/real_estate_trends.jpg
